log:
  level: DEBUG
  filePath: "/var/log/traefik.log"

ping: {}

accessLog:
  filePath: "/var/log/access.log"

api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":80"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    swarmMode: true

http:
  routers:
    dashboard:
      rule: Host(`gboscaro-udemy-ticketing.duckdns.org`) && PathPrefix(`/dashboard`))
      service: api@internal
      middlewares: 
        - auth
  middlewares:
    auth:
      basicAuth:
        users:
          - admin:$apr1$5tchkyn4$2UyHYyx4Op67ERv/Dt8VB1
